### ISSUE TITLE
CSS font classes naming based on voice range

### ISSUE THREAD

**Issue by ryanve** [ryanve/interfaces#9]
names based on https://en.wikipedia.org/wiki/Voice_type

```css
.font-bass { font-size: 1rem; line-height: normal }
.font-baritone { font-size: 1.125rem; line-height: normal }
.font-tenor { font-size: 1.375rem; line-height: normal }
.font-alto { font-size: 1.625rem; line-height: normal }
.font-mezzo { font-size: 2rem; line-height: normal }
.font-soprano { font-size: 3rem; line-height: normal }
```
